### ISSUE TITLE
volume碎片整理问题

### ISSUE THREAD

**Issue by sapluk** [seaweedfs/seaweedfs#4553]
我们现在使用的是0.98版本，准备升到最新版本，但在做碎片整理时遇到些问题，需要您的解答，谢谢

碎片整理时调用`curl [http://masterServerHost:masterServerPort/vol/vacuum?garbageThreshold=0.0`，
但是由于某种原因，我们的单个服务器上部署了多个volume节点，调用master的清理指令时，可能会导致磁盘空间不足而失败，
所以我们在执行的时候，是通过对节点发起请求来进行一个一个的清理工作，即:
```
// weed 0.98
curl "http://volumeServerHost:volumeServerPort/admin/vacuum/check?volume=50&garbageThreshold=0.0"
curl "http://volumeServerHost:volumeServerPort/admin/vacuum/compact?volume=50"
curl "http://volumeServerHost:volumeServerPort/admin/vacuum/commit?volume=50"
```

我们将版本升级到3.51时，调用上述的方法时，服务器响应400,

请问这种方式还在么？我还能通过什么方法进行一个一个文件的清理？

**Comment by wusongANKANG** [comment]
The volume server (after 1.00) does not support the vacuum api, you can use master api to do vacuum operation.
https://github.com/seaweedfs/seaweedfs/wiki/Master-Server-API

It is recommended to use volume.vacuum command  in the weed shell, and you can specify one volume for vacuum each time.

At the same time, it is recommended to upgrade to 3.50 or 3.53 (maybe in a few days), because 3.51 may have a deadlock problem.
