### ISSUE TITLE
Weed shell incorretly resolves volume grpc port

### ISSUE THREAD

**Issue by kasefuchs** [seaweedfs/seaweedfs#5617]
**Describe the bug**
I'm using dynamic port allocation in the Nomad. When I try to remove orphaned data from volume servers, the weed shell requests `<http port> + 10000` instead of the grpc port that is specified when starting volume servers.

**System Setup**

##### Command line

`options.dat` is empty on both servers.

###### Master:
```hcl
[
    "master",
    "-ip.bind=0.0.0.0",
    "-ip=100.70.149.82",
    "-port=29274",
    "-port.grpc=27089",
    "-options=/local/config/options.dat"
]
```

###### Volume:
```json
[
    "volume",
    "-ip.bind=0.0.0.0",
    "-ip=100.108.234.121",
    "-port=30607",
    "-port.grpc=24973",
    "-dir=/local/data",
    "-rack=vixie",
    "-dataCenter=muttias",
    "-options=/local/config/options.dat",
    "-mserver=100.70.149.82:29274.27089"
]
```

All servers are running version 3.67 inside docker containers on Debian 12 nodes.

**Expected behavior**
The weed shell uses the correct port provided by the volume server and successfully deletes the orphaned data.

**Screenshots**
![image](https://github.com/seaweedfs/seaweedfs/assets/64592097/7ecc9a7f-7a17-4858-8460-b1e6b16671fb)

**Comment by NyaMisty** [comment]
Yeah that's a long-standing problem. I've carefully inspected the codebase, and there's toooooo many incorrect usages on "ServerAddress" structs.

I believe there's no simple way to fix this issue because we actually need thorough testing, and testcases for custom grpc port is clearly missing.

I suggest you reserve 1000~10000 consecutive ports, and let seaweedfs to use the default grpc ports. For example let Nomad assign ports between 20000-30000, and reserve 30000-40000 port range for grpc port, letting TCP ephemeral ports to use 40000-65536

**Comment by chrislusf** [comment]
Added a fix. Please help to confirm the fix.

**Comment by kasefuchs** [comment]
> Added a fix. Please help to confirm the fix.

![image](https://github.com/seaweedfs/seaweedfs/assets/64592097/58d36bf9-1f28-4e5b-9a8a-60821a3d7e63)

Now everything works well, waiting for the next release!
